packages:
  - projects/*
  - projects/use-wallet/packages/*
  - projects/use-wallet-ui/packages/*
linkWorkspacePackages: true
onlyBuiltDependencies:
  - '@algorandfoundation/puya-ts'
  - bigint-buffer
  - esbuild
  - keccak
  - sharp
  - workerd
overrides:
  typescript: 5.9.3
  viem: 2.45.3
