name = "x-evm-rpc-server"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "72f5c3bf37e8e96111f551909c08e13e"

[[routes]]
pattern = "x-evm-rpc.algorand.tech"
custom_domain = true
